"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['vmware_guest_url_opener.py']
OPTIONS = {
    'argv_emulation': False,
    'plist': {
        'CFBundleDevelopmentRegion': 'en',
        'NSPrincipalClass': 'NSApplication',
        'NSAppleScriptEnabled': 'YES',
        'LSUIElement': 'YES',
        'CFBundleIdentifier': 'is.syndis.vmware_guest_url_opener',
        'CFBundleURLTypes': [{
            'CFBundleURLName': 'VMWare Guest URL Opener',
            'CFBundleURLSchemes': [
                'HTTP',
                'HTTPS',
            ],
        }],
    }
}


setup(
    app=APP,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
